import React, { useLayoutEffect, useRef, useState } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

/**
 * DotLogo
 * ----------------------------------------------------------------------------
 * A field of dots that:
 *   1. Sits scattered (widely, with continuous ambient drift + size pulsing)
 *      before the section is scrolled into view.
 *   2. Assembles into the real logo shape as the section scrolls into view,
 *      each dot arriving at a slightly randomized moment (not all at once).
 *   3. Keeps gently animating (reduced-amplitude drift/pulse) even after
 *      it has fully assembled, so it never goes fully static.
 *
 * The target coordinates were generated by rasterizing the logo SVG
 * (Group_38.svg) and sampling points inside its filled area on a grid, so
 * the assembled state is a faithful dot-matrix rendering of the real logo.
 *
 * How it works:
 *   - A single scroll-linked value (0 -> 1) is driven by ScrollTrigger with
 *     `scrub`, which smooths/lags the value behind actual scroll position
 *     (this, plus a longer `end` distance, is what makes the reveal feel
 *     slow and eased rather than snapping into place).
 *   - Each dot has its own random "phase" (0 - ~0.55): it only starts
 *     moving toward its target once scroll-progress passes its phase, so
 *     dots arrive at randomized moments across the scroll range.
 *   - Independently of scroll, every dot runs an infinite GSAP "wander"
 *     loop -- tweening a small random offset (x/y/size) with a new random
 *     target + duration each time it completes -- which is what gives the
 *     continuous, non-static organic motion. This keeps running for the
 *     lifetime of the component; its amplitude just gets dialed down
 *     (via `settledWanderScale`) once a dot is assembled, rather than
 *     stopping.
 *   - A single rAF-driven render loop (gsap.ticker) combines
 *     scroll-progress + wander offset every frame and writes directly to
 *     each <circle>'s cx/cy/r attributes.
 *
 * Usage:
 *   <DotLogo />
 *   <DotLogo scatterRadius={4} />                 // spread dots out further
 *   <DotLogo start="top 90%" end="+=1400" scrub={1.5} /> // slower/faster reveal
 *   <DotLogo wanderAmount={10} settledWanderScale={0.6} /> // more ambient motion
 *
 * Requires: gsap  ->  npm install gsap
 * ----------------------------------------------------------------------------
 */

const LOGO_VIEWBOX = { width: 433, height: 282 };

const TARGET_POINTS = [[156.0,0.0],[168.0,0.0],[180.0,0.0],[324.0,0.0],[156.0,12.0],[168.0,12.0],[180.0,12.0],[276.0,12.0],[288.0,12.0],[300.0,12.0],[312.0,12.0],[324.0,12.0],[336.0,12.0],[348.0,12.0],[360.0,12.0],[156.0,24.0],[168.0,24.0],[180.0,24.0],[252.0,24.0],[264.0,24.0],[276.0,24.0],[288.0,24.0],[300.0,24.0],[312.0,24.0],[324.0,24.0],[336.0,24.0],[348.0,24.0],[360.0,24.0],[372.0,24.0],[384.0,24.0],[156.0,36.0],[168.0,36.0],[180.0,36.0],[240.0,36.0],[252.0,36.0],[264.0,36.0],[276.0,36.0],[288.0,36.0],[300.0,36.0],[312.0,36.0],[324.0,36.0],[336.0,36.0],[348.0,36.0],[360.0,36.0],[372.0,36.0],[384.0,36.0],[396.0,36.0],[60.0,48.0],[72.0,48.0],[84.0,48.0],[96.0,48.0],[108.0,48.0],[120.0,48.0],[132.0,48.0],[156.0,48.0],[168.0,48.0],[180.0,48.0],[228.0,48.0],[240.0,48.0],[252.0,48.0],[264.0,48.0],[276.0,48.0],[360.0,48.0],[372.0,48.0],[384.0,48.0],[396.0,48.0],[408.0,48.0],[36.0,60.0],[48.0,60.0],[60.0,60.0],[72.0,60.0],[84.0,60.0],[96.0,60.0],[108.0,60.0],[120.0,60.0],[132.0,60.0],[144.0,60.0],[156.0,60.0],[168.0,60.0],[180.0,60.0],[228.0,60.0],[240.0,60.0],[252.0,60.0],[264.0,60.0],[384.0,60.0],[396.0,60.0],[408.0,60.0],[24.0,72.0],[36.0,72.0],[48.0,72.0],[60.0,72.0],[72.0,72.0],[84.0,72.0],[96.0,72.0],[108.0,72.0],[120.0,72.0],[132.0,72.0],[144.0,72.0],[156.0,72.0],[168.0,72.0],[180.0,72.0],[216.0,72.0],[228.0,72.0],[240.0,72.0],[252.0,72.0],[384.0,72.0],[396.0,72.0],[408.0,72.0],[420.0,72.0],[24.0,84.0],[36.0,84.0],[48.0,84.0],[60.0,84.0],[132.0,84.0],[144.0,84.0],[156.0,84.0],[168.0,84.0],[180.0,84.0],[216.0,84.0],[228.0,84.0],[240.0,84.0],[396.0,84.0],[408.0,84.0],[420.0,84.0],[12.0,96.0],[24.0,96.0],[36.0,96.0],[48.0,96.0],[144.0,96.0],[156.0,96.0],[168.0,96.0],[180.0,96.0],[216.0,96.0],[228.0,96.0],[240.0,96.0],[396.0,96.0],[408.0,96.0],[420.0,96.0],[12.0,108.0],[24.0,108.0],[36.0,108.0],[156.0,108.0],[168.0,108.0],[180.0,108.0],[216.0,108.0],[228.0,108.0],[240.0,108.0],[396.0,108.0],[408.0,108.0],[420.0,108.0],[432.0,108.0],[12.0,120.0],[24.0,120.0],[36.0,120.0],[156.0,120.0],[168.0,120.0],[180.0,120.0],[216.0,120.0],[228.0,120.0],[240.0,120.0],[396.0,120.0],[408.0,120.0],[420.0,120.0],[432.0,120.0],[0.0,132.0],[12.0,132.0],[24.0,132.0],[36.0,132.0],[156.0,132.0],[168.0,132.0],[180.0,132.0],[216.0,132.0],[228.0,132.0],[240.0,132.0],[396.0,132.0],[408.0,132.0],[420.0,132.0],[12.0,144.0],[24.0,144.0],[36.0,144.0],[156.0,144.0],[168.0,144.0],[180.0,144.0],[216.0,144.0],[228.0,144.0],[240.0,144.0],[396.0,144.0],[408.0,144.0],[420.0,144.0],[12.0,156.0],[24.0,156.0],[36.0,156.0],[156.0,156.0],[168.0,156.0],[180.0,156.0],[216.0,156.0],[228.0,156.0],[240.0,156.0],[384.0,156.0],[396.0,156.0],[408.0,156.0],[420.0,156.0],[12.0,168.0],[24.0,168.0],[36.0,168.0],[48.0,168.0],[144.0,168.0],[156.0,168.0],[168.0,168.0],[180.0,168.0],[216.0,168.0],[228.0,168.0],[240.0,168.0],[372.0,168.0],[384.0,168.0],[396.0,168.0],[408.0,168.0],[24.0,180.0],[36.0,180.0],[48.0,180.0],[60.0,180.0],[132.0,180.0],[144.0,180.0],[156.0,180.0],[168.0,180.0],[216.0,180.0],[228.0,180.0],[240.0,180.0],[360.0,180.0],[372.0,180.0],[384.0,180.0],[396.0,180.0],[408.0,180.0],[24.0,192.0],[36.0,192.0],[48.0,192.0],[60.0,192.0],[72.0,192.0],[84.0,192.0],[96.0,192.0],[108.0,192.0],[120.0,192.0],[132.0,192.0],[144.0,192.0],[156.0,192.0],[216.0,192.0],[228.0,192.0],[240.0,192.0],[264.0,192.0],[276.0,192.0],[288.0,192.0],[300.0,192.0],[312.0,192.0],[324.0,192.0],[336.0,192.0],[348.0,192.0],[360.0,192.0],[372.0,192.0],[384.0,192.0],[396.0,192.0],[36.0,204.0],[48.0,204.0],[60.0,204.0],[72.0,204.0],[84.0,204.0],[96.0,204.0],[108.0,204.0],[120.0,204.0],[132.0,204.0],[144.0,204.0],[216.0,204.0],[228.0,204.0],[240.0,204.0],[264.0,204.0],[276.0,204.0],[288.0,204.0],[300.0,204.0],[312.0,204.0],[324.0,204.0],[336.0,204.0],[348.0,204.0],[360.0,204.0],[372.0,204.0],[384.0,204.0],[60.0,216.0],[72.0,216.0],[84.0,216.0],[96.0,216.0],[108.0,216.0],[120.0,216.0],[132.0,216.0],[216.0,216.0],[228.0,216.0],[240.0,216.0],[264.0,216.0],[276.0,216.0],[288.0,216.0],[300.0,216.0],[312.0,216.0],[324.0,216.0],[336.0,216.0],[348.0,216.0],[360.0,216.0],[0.0,252.0],[12.0,252.0],[24.0,252.0],[36.0,252.0],[48.0,252.0],[60.0,252.0],[72.0,252.0],[84.0,252.0],[96.0,252.0],[108.0,252.0],[120.0,252.0],[132.0,252.0],[144.0,252.0],[156.0,252.0],[168.0,252.0],[180.0,252.0],[0.0,264.0],[12.0,264.0],[24.0,264.0],[36.0,264.0],[48.0,264.0],[60.0,264.0],[72.0,264.0],[84.0,264.0],[96.0,264.0],[108.0,264.0],[120.0,264.0],[132.0,264.0],[144.0,264.0],[156.0,264.0],[168.0,264.0],[180.0,264.0],[0.0,276.0],[12.0,276.0],[24.0,276.0],[36.0,276.0],[48.0,276.0],[60.0,276.0],[72.0,276.0],[84.0,276.0],[96.0,276.0],[108.0,276.0],[120.0,276.0],[132.0,276.0],[144.0,276.0],[156.0,276.0],[168.0,276.0],[180.0,276.0]];

// Seeded PRNG so the scatter layout is stable across renders/reloads,
// while still looking organic.
function mulberry32(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const lerp = (a, b, t) => a + (b - a) * t;
const clamp01 = (v) => Math.max(0, Math.min(1, v));
const easeOutCubic = (t) => 1 - Math.pow(1 - t, 3);

/**
 * Builds each dot's scattered starting position (spread widely around --
 * and beyond -- the logo's bounding box), its target logo position, and
 * the randomized parameters (start/end size, opacity, arrival phase) that
 * drive its individual behavior.
 */
function buildLayout(points, scatterRadius, seed) {
  const rand = mulberry32(seed);
  const { width, height } = LOGO_VIEWBOX;

  return points.map(([tx, ty]) => {
    const jitterX = (rand() - 0.5) * width * scatterRadius;
    const jitterY = (rand() - 0.5) * height * scatterRadius * 1.6;

    return {
      sx: tx + jitterX,
      sy: ty + jitterY,
      tx,
      ty,
      startR: 2 + rand() * 6.5,
      endR: 2.6 + rand() * 1.6,
      startOpacity: 0.28 + rand() * 0.5,
      // Randomizes *when* (across the scroll range) this dot starts
      // moving toward its target -- this is what makes the assembly
      // feel organic instead of every dot snapping together at once.
      phase: rand() * 0.55,
    };
  });
}

export default function DotLogo({
  width = "100%",
  maxWidth = 560,
  scatterRadius = 0.8,
  dotColor = "#111111",
  start = "top 50%",
  end = "center 50%",
  scrub = 0.2,
  seed = 42,
  wanderAmount = 5, // px (in the 433x282 viewBox coordinate space) of ambient drift
  wanderMinDuration = 0.7,
  wanderMaxDuration = 1.6,
  settledWanderScale = 0.25, // ambient motion kept once a dot has assembled (0 = fully still)
  className = "",
  style = {},
}) {
  const containerRef = useRef(null);
  const dotRefs = useRef([]);
  const [layout] = useState(() => buildLayout(TARGET_POINTS, scatterRadius, seed));
  const progressRef = useRef(0);

  useLayoutEffect(() => {
    const dots = dotRefs.current;
    const wander = layout.map(() => ({ x: 0, y: 0, r: 0 }));
    const wanderTweens = [];

    // ---- Ambient wander: continuous organic drift + size pulsing.
    // Runs forever (mount to unmount) independent of scroll position.
    function loopWander(i) {
      wanderTweens[i] = gsap.to(wander[i], {
        x: gsap.utils.random(-wanderAmount, wanderAmount),
        y: gsap.utils.random(-wanderAmount, wanderAmount),
        r: gsap.utils.random(-wanderAmount * 0.35, wanderAmount * 0.35),
        duration: gsap.utils.random(wanderMinDuration, wanderMaxDuration),
        ease: "sine.inOut",
        onComplete: () => loopWander(i),
      });
    }
    layout.forEach((_, i) => loopWander(i));

    // ---- Scroll-driven assembly progress (0 -> 1), smoothed via scrub so
    // it lags gently behind the actual scroll position instead of snapping.
    const progressProxy = { v: 0 };
    const progressTween = gsap.to(progressProxy, {
      v: 1,
      ease: "none",
      scrollTrigger: {
        trigger: containerRef.current,
        start,
        end,
        scrub,
        onLeave: () => {
          progressRef.current = 1;
        },
        onLeaveBack: () => {
          progressRef.current = 0;
        },
      },
      onUpdate: () => {
        progressRef.current = progressProxy.v;
      },
    });

    // ---- Per-frame render: combine scroll progress + ambient wander and
    // write straight to the SVG attributes (cheap, avoids extra tweens).
    function render() {
      const globalP = progressRef.current;
      for (let i = 0; i < dots.length; i++) {
        const el = dots[i];
        if (!el) continue;
        const d = layout[i];
        const w = wander[i];

        const local = easeOutCubic(clamp01((globalP - d.phase) / (1 - d.phase)));
        const wanderScale = lerp(1, settledWanderScale, local);

        const cx = lerp(d.sx, d.tx, local) + w.x * wanderScale;
        const cy = lerp(d.sy, d.ty, local) + w.y * wanderScale;
        const r = Math.max(0.4, lerp(d.startR, d.endR, local) + w.r * wanderScale);
        const opacity = lerp(d.startOpacity, 1, local);

        el.setAttribute("cx", cx.toFixed(2));
        el.setAttribute("cy", cy.toFixed(2));
        el.setAttribute("r", r.toFixed(2));
        el.style.opacity = opacity;
      }
    }

    render(); // paint the correct initial state immediately, before the first tick
    gsap.ticker.add(render);

    return () => {
      gsap.ticker.remove(render);
      wanderTweens.forEach((tw) => tw && tw.kill());
      progressTween.scrollTrigger && progressTween.scrollTrigger.kill();
      progressTween.kill();
    };
  }, [layout, start, end, scrub, wanderAmount, wanderMinDuration, wanderMaxDuration, settledWanderScale]);

  return (
    <div
      ref={containerRef}
      className={className}
      style={{
        position: "relative",
        width,
        maxWidth,
        aspectRatio: `${LOGO_VIEWBOX.width} / ${LOGO_VIEWBOX.height}`,
        margin: "0 auto",
        ...style,
      }}
    >
      <svg
        viewBox={`0 0 ${LOGO_VIEWBOX.width} ${LOGO_VIEWBOX.height}`}
        style={{ position: "absolute", inset: 0, width: "100%", height: "100%", overflow: "visible" }}
        aria-label="Logo"
        role="img"
      >
        {TARGET_POINTS.map((_, i) => (
          <circle key={i} ref={(el) => (dotRefs.current[i] = el)} fill={dotColor} />
        ))}
      </svg>
    </div>
  );
}
